### PR TITLE
Vanity profile

### PR DESCRIPTION
**Pull request by hamidra**
added the vanity profile as a new page.
Not sure how Wouter route works with subfolders so if deployed and failed probably we need to set hash routes to make it work with url subfolders in githubpages!

- shows the profile in top section with Delegate All button.
Screenshot 2023-04-20 at 5 14 09 PM

- shows any active delegates in bottom section with Undelegate Button
Screenshot 2023-04-20 at 5 14 31 PM

### CODE REVIEW

**Comment by dnlklmn** [comment]
i think the best would be if this worked as a real subpage, and had an easy way to navigate back to the home screen (where you'd also see active delegations if you have something set up)

i'm not sure we have to add delegate only certain tracks here just yet - delegate all might turn out to be sufficient

wdyt?

image

**Review by dnlklmn — CHANGES_REQUESTED** [review]
one way or the other we need a back btn for sure, wdyt

**Comment by hamidra** [comment]
Agreed. Back button should be added. I have no strong opinion regarding removing the card style and showing the info with no card border. The main question is what should it show when all or some of the tracks are already delegated?!

**Comment by hamidra** [comment]
I thought having the active delegates on that page helps to clarify what is currently delegated and if they would like to undelegate  them to delegate it to the new account?! I was not sure what are other alternative UXs?

**Comment by hamidra** [comment]
Made the changed to adopt the new design!

**Review by jeluard — APPROVED** [review]

**Pull request merged**
